-- Insert sample regulatory updates data
INSERT INTO regulatory_updates (title, summary, risk_level, dev_action, category, dev_impact_score, source_url, detailed_analysis) VALUES
('RBI Master Direction on Digital Lending', 'New guidelines mandate that all digital lending apps must display upfront disclosure of fees, penal charges, and cooling-off period for borrowers. LSPs must ensure transparent loan service agreements.', 'high', 'Update loan disclosure UI to show all fee breakdowns before loan confirmation. Implement 3-day cooling-off period logic.', 'Digital Lending', 8, 'https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=12166', ARRAY['All fees and charges payable by borrowers to be displayed upfront on the app', 'Digital lenders must provide a Key Fact Statement (KFS) to borrowers', 'Cooling-off period mandatory for loan cancellation without penalty', 'Data collection must be need-based with explicit borrower consent']),

('SEBI Circular on Algo Trading Registration', 'SEBI mandates that all algorithmic trading strategies must be registered with stock exchanges. Retail investors using third-party algo providers must provide unique identification.', 'high', 'Implement algo registration flow with NSE/BSE API integration. Add unique algo ID tracking per user strategy.', 'Trading', 9, 'https://www.sebi.gov.in/legal/circulars/jan-2024/framework-for-algorithmic-trading_77896.html', ARRAY['All algo strategies must be approved by exchanges before deployment', 'Unique Client Code (UCC) mandatory for each algo trading account', 'Kill switch implementation required for all algo systems', 'Audit trail of all algo orders must be maintained for 7 years']),

('RBI Guidelines on Payment Aggregators', 'Updated PA-PG guidelines require enhanced due diligence for onboarding merchants. Escrow account requirements strengthened with daily settlement mandates.', 'medium', 'Review merchant onboarding flow for KYC compliance. Ensure escrow settlement logic runs daily.', 'Payments', 6, 'https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12462&Mode=0', ARRAY['Net worth requirement for PAs increased to Rs 25 crore', 'Mandatory background checks for all onboarded merchants', 'Escrow accounts must be settled within T+1', 'Customer grievance redressal mechanism required within 48 hours']),

('SEBI Amendments to Listing Obligations', 'New disclosure requirements for listed entities regarding related party transactions. Quarterly disclosures must include detailed RPT analysis.', 'low', 'Add RPT disclosure module to quarterly reporting dashboard. Implement threshold-based alerts.', 'Compliance', 4, 'https://www.sebi.gov.in/legal/regulations/jan-2024/sebi-listing-obligations_77456.html', ARRAY['Related party transactions above threshold require shareholder approval', 'Quarterly disclosure format updated with additional fields', 'Audit committee must review all RPTs before disclosure', 'Material RPT threshold reduced from 10% to 5% of turnover']),

('RBI Framework for Account Aggregators', 'Revised AA framework introduces new data sharing protocols and consent artifact specifications. FIPs must implement standardized APIs.', 'medium', 'Migrate to AA 2.0 API specifications. Update consent management module with new artifact format.', 'Data Sharing', 7, 'https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=12285', ARRAY['Consent artifacts must include purpose and duration clearly', 'FIU must implement standardized data request formats', 'Session-based data fetch deprecated in favor of async model', 'Dispute resolution mechanism mandatory between AAs and FIPs']),

('SEBI Guidelines on ESG Disclosures', 'BRSR Core disclosures made mandatory for top 1000 listed companies. ESG ratings must be obtained from SEBI-registered agencies only.', 'low', 'Integrate BRSR reporting template. Add ESG score display to company profiles for applicable entities.', 'ESG', 3, 'https://www.sebi.gov.in/legal/circulars/jul-2023/brsr-core-framework_73854.html', ARRAY['Business Responsibility and Sustainability Report mandatory annually', 'ESG ratings from unregistered agencies not valid for compliance', 'Reasonable assurance required for BRSR Core disclosures', 'Supply chain ESG assessment to be included from FY 2024-25']);